name: My first workflow
on:
  push:
    branches:
    - "main"
jobs:
  echo_the_date:
    runs-on: ubuntu-latest
    env:
      OPENWEATHERMAP_KEY: ${{ secrets.openweathermap_api }}
    steps:
    - name: echo the date
      run: echo "The current time and date is $(date)"
    - name: echo the current branch
      run: echo ${{ github.ref_name }}

  test_and_deploy:
    runs-on: ubuntu-latest
    env:
      OPENWEATHERMAP_KEY: ${{ secrets.openweathermap_api }}
    steps:
    - name: SetrUp JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: 3.8.2
    - name: Checkout the source
      uses: actions/checkout@v3
    - name: Run Test
      run: mvn clean test
    - name: Deploy to heroku
      uses: akhileshns/heroku-deploy@v3.12.12 
      with:
        heroku_api_key: ${{secrets.HEROKU_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.EMAIL}}
        branch: ${{github.ref_name}}

